name: GIPHY generator

on: workflow_dispatch

jobs:
  giphy-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: read/write
      pull-requests: read/write
      
    steps:
      - name: GIPHY Generator
        id: giphy_generator
        uses: IAmHughes/giphy-generator@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
        with:
          lang: 'en'
