name: GIPHY generator

on: 
  workflow_dispatch: 
  
jobs:
  giphy-generator: 
    runs-on: ubuntu-latest

    steps: 
      - name: GIPHY Generator
        uses: IAmHughes/giphy-generator@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
        with:
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          rating: 'g'
          lang: 'en'
